spring:
  profiles:
    default: local
  application:
    name: price-service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Trace everything, but please use 0.1 for Prod
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
