spring:
  profiles:
    default: local
  application:
    name: price-service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Trace everything, but please use 0.1 for Prod
    baggage:
      correlation:
        fields: x-request-id, x-application-id
      remote-fields: ${management.tracing.baggage.correlation.fields}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      my_custom_tag: ${spring.application.name}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}, %X{x-request-id:-}, %X{x-application-id:-}]'
