server:
  port: 8090

spring:
  boot:
    admin:
      client:
        url: http://localhost:9999

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Default value
