apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: application
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        type: spring-boot
    spec:
      containers:
        - name: order-app
          image: bitxon/order-app
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db-service.default.svc.cluster.local:5432/postgres"
            - name: HTTP_PRICE_CLIENT_URL
              value: "http://price-service.default.svc.cluster.local:8080"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin-service.default.svc.cluster.local:9411/api/v2/spans"