apiVersion: v1
kind: Service
metadata:
  name: price-service
spec:
  type: ClusterIP
  selector:
    app: price
  ports:
    - name: application
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: price
  template:
    metadata:
      labels:
        app: price
        type: spring-boot
    spec:
      containers:
        - name: price-app
          image: bitxon/price-app
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin-service.default.svc.cluster.local:9411/api/v2/spans"