server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  boot:
    admin:
      client:
        url: http://localhost:9999

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Default value

http:
  price-client:
    url: http://localhost:8090
