server:
  port: 8080

spring:
  profiles:
    default: local
  application:
    name: order-service
  flyway:
    default-schema: postgres
    fail-on-missing-locations: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Trace everything, but please use 0.1 for Prod
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'