server:
  port: 8080
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        service-labels:
          type: spring-boot


logging:
  level:
    org.springframework.cloud.kubernetes: TRACE
    de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener: DEBUG
